#%RAML 1.0 SecurityScheme

description: |
  This API supports Bearer Authentication.
type: x-bearer
describedBy:
  headers:
    Authorization:
      description: |
        Used to send a valid Bearer access token.
      type: string
  responses:
    401:
      description: |
        Unauthorized. Bad or expired token.
    403:
      description: |
        Forbidden. The server understood the request, but is refusing to fulfill it.
