#%RAML 1.0
title: collection
version: v1

resourceTypes:
  Restful:
    description: Collection of available <<resourcePathName>>
    get:
      description: Get list of <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<type>>
              example: <<customExampleGetList>>
    post:
      description: Create a new <<resourcePathName|!singularize>>
      body:
        application/x-www-form-urlencoded:
          type: <<model>>
      responses:
        200:
          body:
            application/json:
              example: <<customExamplePost>>
    /{id}:
      get:
        description: Get a <<resourcePathName|!singularize>>
        responses:
          200:
            body:
              application/json:
                type: <<type>>
                example: <<customExampleGetById>>
      put:
        description: Put update a <<resourcePathName|!singularize>>
        body:
          application/x-www-form-urlencoded:
            type: <<model>>
        responses:
          200:
            body:
              application/json:
                type: object
                example: <<customExamplePut>>
      delete:
        description: Delete a <<resourcePathName|!singularize>>
        responses:
          200:
            body:
              application/json:
                type: object
                example: <<customExampleDelete>>
